### ISSUE TITLE
Find out what to do about tabbed content boxes

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-eic#16]
Some of the EIC pages (e.g. [Air Quality](https://gis.earthdata.nasa.gov/portal/apps/sites/#/earth-information-center/pages/air-quality)) include content boxes like this one:

![image](https://github.com/NASA-IMPACT/veda-config-eic/assets/3404817/fb7b4414-c912-48c2-820d-30e46e15c893)

What do we do about these for the first release? 

1. Can they be embedded from their original source as-is? 
2. Can we just turn this content into paragraphs?

## Acceptance criteria

- [x] Found out what to do with tabbed content boxes

**Comment by agurvich** [comment]
Probably easiest to just turn this into paragraphs, I can go ahead and do that.
