### ISSUE TITLE
Revisit top nav for visit and teach pages

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-eic#22]
The additional teach and visit pages are currently "hidden" behind a hamburger/kebab menu on the secondary nav (top right), using existing functionality of VEDA UI.

There are concerns that these key features of the EIC are not visible enough to users this way.

Can we come up with another quick fix for the 17 Nov release?

> I would definitely like to explore the responsive solution, though I know we don't really have a lot of time. Putting the Visit and Teach into the 3 dots menu makes them hard to find. I also think we should consider replacing the 3 dots with a hamburger for all screen sizes since they function (almost) the same and 3 dots is usually associated with customization/options in this context. Or maybe putting the word "More" could invite people to click it? I'm just afraid no one will find the pages  as it is now :\

_Originally posted by @agurvich in https://github.com/NASA-IMPACT/veda-config-eic/issues/5#issuecomment-1809502284_

Related: https://github.com/NASA-IMPACT/veda-ui/pull/748#issue-1993319081

## Acceptance criteria

- [x] Decided on what to do to make visit and teach features more discoverable

**Comment by j08lue** [comment]
We can also put these items on the secondary nav for now. However, at a small range of viewport width (around 1000 pixels), this will currently cause the nav texts to wrap:

![image](https://github.com/NASA-IMPACT/veda-config-eic/assets/3404817/650f7c4f-4eae-4273-abe2-69ffa2f8b353)

While even narrower viewports cause the nav to be collapsed into a hamburger menu:

![image](https://github.com/NASA-IMPACT/veda-config-eic/assets/3404817/3c0ffc54-3f9e-4e4b-85c7-accbf9f29792)

Should we accept that little glitch for now, so we can have these nav items visible, @agurvich?

**Comment by hanbyul-here** [comment]
Heads-up that how the nav will look/collapse its style will vary depending on the nav's state. ex. We enlarged logo size (requires more space), but made the nav items to be not in all caps (requires less space). 

so the nav looks like below now (but it might change depending on nav.)

<img width="964" alt="Screen Shot 2023-11-16 at 11 53 29 AM" src="https://github.com/NASA-IMPACT/veda-config-eic/assets/4583806/bde68191-e48c-44b7-b687-068ba87f764e">

**Comment by j08lue** [comment]
Decision was made to keep the items visible and accept the glitch for now.
