### ISSUE TITLE
EIC Styling Polishing and Tweaks

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-config-eic#30]
Dev
- [x] Landing page - Arrange Heading structure
- [x] Landing page - Heading style 
- [x] Landing page - make logo arrangement according to design (and possibly logo size adjustment - larger logos?)
- [x] Theme Cards - hover state
- [ ] General - focus + hover state (Sandra -> In Progress)
- [x] Carousel - current slide number (low priority)

Contents
- [x] Landing page - Attribution Text for Hero image
- [ ] Landing page - Blurry Logos for FEMA, USGS
- [x] Landing page - Google Form for 'contact us' : This can be encoded in .env file like this: https://github.com/NASA-IMPACT/veda-config-ghg/blob/develop/.env#L23
- [x] Landing page - Responsible official's name
- [x] General - Text for loading page https://github.com/NASA-IMPACT/veda-config-eic/blob/develop/.env#L5
- [x] Contact Email - https://github.com/NASA-IMPACT/veda-config-eic/blob/develop/.env#L8
- [x] Disclaimer modals - change text GHGC -> EIC
- [x] Data Catalog Banner texts from configuration - https://github.com/NASA-IMPACT/veda-config-eic/blob/develop/veda.config.js#L43-L45

**Comment by sandrahoang686** [comment]
@faustoperez - Are there figma links to:
*  General - focus + hover state
*  Theme Cards - hover state
?

**Comment by hanbyul-here** [comment]
@faustoperez heads up external-link is veda-ui core component, and It is not very straightforward to give different styles for 'external link' cards without cutting a new release from `veda-ui`. I suggest we do hover/focus of the components that live inside of EIC instance for now, and do the improvement of core ui components in the short future.

**Comment by j08lue** [comment]
As good as it gets. Great work!

**Comment by faustoperez** [comment]
Great work, looking good!
