### ISSUE TITLE
Create functionality to include a grid of content cards (stories, external links, datasets) for a manually selected set of items in a page or story

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-eic#4]
## Existing functionality

To present a set of related/highlighted items within a page, we currently have three available features in VEDA UI:

1. Automatically populated catalogs of content items (`/stories` for stories and `/data-catalog` for datasets)
2. Featured Stories/Datasets ([docs](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md)) - populated automatically from items that are configured as `featured: true`
3. Related Content ([docs](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md)) - automatically populated from items that are listed in the `related` tag

## Why none of these fulfil the needs out of the box

Since the EIC has more types of items than stories and datasets and we want to use `stories` for all of these (theme features, visitor features, teaching features), the automatic push/filter kind of method might be too cumbersome to hack to support this.

Also, the grouping pages need context and perhaps the collection of featured items would be placed somewhere embedded in content and there might also be several of such collections.

## Possible solution

Perhaps just an MDX component that users can put anywhere, specify the title, and otherwise just list a number of items to show cards for, in the order provided, without filtering or sorting functionality.

What to do about the pills? They could in principle still link to `/stories` or `/data-catalog`, filtered accordingly.

## Acceptance criteria

- [ ] A page for EIC is able to embed a hand-picked collection of features (cards)

**Comment by hanbyul-here** [comment]
Are we sure that we cannot use related-contents field? Considering we consider external links just as stories, I think we can use related-content? Related content can be curated through mdx, like this: https://github.com/NASA-IMPACT/veda-config-eic/pull/9/files#diff-6034628120783296ca2276d02fa210daa65f1520d4f2191ee9044d083a79fc37R14-R18 (Only stories now, but it can be dataset.)

**Comment by j08lue** [comment]
> Are we sure that we cannot use related-contents field?

Just thinking that a story will be related content only in one context (e.g. on a theme intro page), not another (e.g. the teach page).
