### ISSUE TITLE
Issues discovered on production deployment

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-eic#57]
@slesaad and other reviewers caught these issues / things to fix:

- [x] Analysis jobs were failing - cure: #56 
- [x] Nothing in sustainable energy stories (can we remove the title if there's no stories)?
   ![image](https://github.com/NASA-IMPACT/veda-config-eic/assets/3404817/dea56f53-a3dc-4fe2-9473-e42e4d5dab3c)
- [x] The carousel numbering is messed up, the total is one more than there are items
   ![image](https://github.com/NASA-IMPACT/veda-config-eic/assets/3404817/4337529a-f592-4aa1-81ba-2cb25a26b2e0)
- [x] Some of the "theme" pages have this random 0 at the end for some reason (see the last image)
   ![image](https://github.com/NASA-IMPACT/veda-config-eic/assets/3404817/95ae8961-1b16-4986-afd4-a23ba54dfff7)
   Pages affected:
   - https://earth-information-center.netlify.app/stories/agriculture
   - https://earth-information-center.netlify.app/stories/disasters
- [x] The google form linked in the about page goes to the "edit" link instead of "view"

## Acceptance criteria

- [ ] Fixed all or opened tickets to track them further

**Comment by j08lue** [comment]
Running notes regarding the random 0 on the `AG_` and `DIS` theme pages:

1. First hypothesis: the zero occurred on all pages with the carousel. Disproven: `AQ_` has a carousel, too, but no 0.

**Comment by j08lue** [comment]
Re google form links: The link is always just `https://docs.google.com/forms/d/1mDgFqUsNv90Js7pERNDbmyN5RksztIy5ZZojWD0n5Pg`

When you open it, you get forwarded to `/edit`.

**Comment by slesaad** [comment]
@j08lue for the form, try appending /viewform to the url

**Comment by j08lue** [comment]
Re carousel numbering

Total was

https://github.com/NASA-IMPACT/veda-config-eic/blob/fed2131a5436ce9a9ef1f0b7ef751ceea9fa14de/overrides/common/embedded-video-carousel.tsx#L142

Trying what happens when I remove the `+1`.

**Comment by j08lue** [comment]
All addressed. If you are online anyways, pls feel free to review, @slesaad, else I'll just rookie-merge 10 min from now.
