### ISSUE TITLE
Update meta image for EIC

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-config-eic#67]
# Description
The meta image for earth.gov is still the ghg image - see here https://github.com/NASA-IMPACT/veda-config-eic/blob/develop/static/meta/meta-image.png. Sharing earth.gov on social media will show the GHG image.

It needs to be updated.

# Acceptance Criteria
- [x] Meta image updated

**Comment by j08lue** [comment]
Ah, we missed that.

I can ask @faustoperez first thing tomorrow, but that will be a bit last-minute.

Until then, let's quickly try some screen shots of the home page. The 3x3 theme grid is quite recognizable, but that gives us a portrait image:

![eic-home-social](https://github.com/NASA-IMPACT/veda-config-eic/assets/3404817/caa8a91e-afb8-4f39-b7f2-85c74d7628b7)

**Comment by slesaad** [comment]
yeah, dunno how portrait would look

what do you think about this?
![image](https://github.com/NASA-IMPACT/veda-config-eic/assets/7830949/08582aec-ef53-4557-a2c1-46f9d9a8202c)

**Comment by j08lue** [comment]
That is presentable, @slesaad, let us put that on for now and see whether we get a chance to improve on it before launch. 👍

**Comment by slesaad** [comment]
https://github.com/NASA-IMPACT/veda-config-eic/pull/68

**Comment by j08lue** [comment]
I tried removing the text blob:
 
![eic-social-top-16-9](https://github.com/NASA-IMPACT/veda-config-eic/assets/3404817/85cc7061-9694-4683-b167-ef59c63958d0)

But let's rather see whether we can get the professionals do fix this. 😅

**Comment by slesaad** [comment]
i do like that!
