### ISSUE TITLE
EIC landing / home page design and implementation

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-eic#8]
## Design in progress

Design of the EIC landing page is in progress, ETA end of this week, @faustoperez 

## Implementation outlook at time of writing

Implementation will _probably_ require

1. Creation of a new component for X (grid of cards of variable width + button?)
2. Creation of a new component for Y (feature about GHG Center)
3. ...?

## Acceptance criteria

- [x] Landing page is up ✨

**Comment by agurvich** [comment]
Here is the first draft of the movie that should go in the header:
https://svs.gsfc.nasa.gov/prepub/abg/fade-globes.mp4

I have to fight with the registration and timing still but hopefully this should give @faustoperez an idea of the colorscheme/variation.

**Comment by faustoperez** [comment]
Here's the design we presented yesterday at the weekly earth.gov Content & Dev Tag-Up

<img width="1440" alt="EIC - Homepage" src="https://github.com/NASA-IMPACT/veda-config-eic/assets/12268629/4b33b78c-0cf7-49b2-8753-cefe0f5ca81f">

And the link to the Figma file 👉 https://www.figma.com/file/2Vd0SDhFOTBJaYioJPr0Ei/Earth.gov?type=design&node-id=22%3A7249&mode=design&t=5nz6ca4xXmLF7ZUs-1

**Comment by faustoperez** [comment]
>  I also think we may need to experiment with a mask (because the background is not fully black)

@agurvich It would be great if you could export the video with a solid dark background instead of the gradient. I think we can make the background disappear through CSS blending modes. This is the "raw" image used in the header of the design in the message above for reference:

![nasa-vhSz50AaFAs-unsplash](https://github.com/NASA-IMPACT/veda-config-eic/assets/12268629/cb622b59-ee71-46d6-9703-c13e5aaff4ef)

Hope this helps!

**Comment by sandrahoang686** [comment]
This should not include page-header and navigation but only the home page content

**Comment by j08lue** [comment]
> This should not include page-header and navigation

Do you mean we should have a separate ticket for those? 💡

**Comment by sandrahoang686** [comment]
@j08lue I spoke to @hanbyul-here  and she mentioned that the page-header/menu navigation shouldn't be a part of this ticket. So if we dont have a ticket i guess we should make one but otherwise i'd happily take the page-header one, its fine with me

**Comment by j08lue** [comment]
Please do, thanks @sandrahoang686!

**Comment by agurvich** [comment]
> > I also think we may need to experiment with a mask (because the background is not fully black)
> 
> @agurvich Thanks for sending the video, looking good! It would be great if you could export the video with a solid dark background instead of the gradient. I think we can make the background disappear through CSS blending modes. This is the "raw" image used in the header of the design in the message above for reference:
> 
> ![nasa-vhSz50AaFAs-unsplash](https://user-images.githubusercontent.com/12268629/281440696-cb622b59-ee71-46d6-9703-c13e5aaff4ef.jpg)
> 
> Hope this helps!

Hey @faustoperez , sorry for the delay on this. Here's what I came up with. In putting this together I did end up making a pretty neat tool that will allow us to make a much better version in the future though!

https://svs.gsfc.nasa.gov/prepub/abg/eic_globe.mp4

**Comment by faustoperez** [comment]
> In putting this together I did end up making a pretty neat tool that will allow us to make a much better version in the future though!

That's great @agurvich! Looking good!

I'll play today with blending modes on Figma and report back. Thanks!

**Comment by faustoperez** [comment]
These are the 3 blending mode options that work with the proposed video and the current header colors:

<img width="1627" alt="image" src="https://github.com/NASA-IMPACT/veda-config-eic/assets/12268629/1956ff07-9385-4ca8-8999-abfa2d05824c">

My choice would be to go with Overlay mode, though it darkens the primary color used on the header (but it's still on brand and fits with the rest of the page). To make it work we need to extend the background video to the whole header including the menu, center the video at 100% width and use Overlay as blending mode at 100% opacity. Here's what it looks like:

<img width="1440" alt="Homepage v2" src="https://github.com/NASA-IMPACT/veda-config-eic/assets/12268629/319c8977-8fef-4d79-9416-c5aafefc9415">

Shall we go ahead @agurvich ? Thanks!

@sandrahoang686
