### ISSUE TITLE
Broken figure on NASA HQ page

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-eic#86]
![image](https://github.com/NASA-IMPACT/veda-config-eic/assets/3404817/73780c36-8529-4f18-9f7b-3c605ec65506)

https://earth.gov/stories/nasa_headquarters

**Comment by agurvich** [comment]
Fixed in #87 , see: https://deploy-preview-87--earth-information-center.netlify.app/stories/nasa_headquarters
